### ISSUE TITLE
Panic with leafwing input and debug logging

### ISSUE THREAD

**Issue by AndreasHGK** [cBournhonesque/lightyear#655]
I just got a panic not long after connecting my client to a headless server: (this panic occurs on the server so I think it is caused by lightyear)
```
2024-10-02T16:01:12.136926Z DEBUG buffer_replication_messages: lightyear::shared::replication::send: Send replication update message_id=MessageId(6733) group_id=ReplicationGroupId(4294967316) bevy_tick=Tick { tick: 3607207 } tick=Tick(314)
2024-10-02T16:01:12.137012Z DEBUG lightyear::shared::replication::send: Update channel ack_tick group_id=ReplicationGroupId(4294967316) bevy_tick=Tick { tick: 3445845 } tick=Tick(296)
2024-10-02T16:01:12.137015Z DEBUG lightyear::shared::replication::send: Update channel ack_tick group_id=ReplicationGroupId(4294967316) bevy_tick=Tick { tick: 3443563 } tick=Tick(295)
2024-10-02T16:01:12.137019Z DEBUG lightyear::shared::replication::send: Update channel ack_tick group_id=ReplicationGroupId(4294967316) bevy_tick=Tick { tick: 3443179 } tick=Tick(295)
2024-10-02T16:01:12.137022Z DEBUG lightyear::shared::replication::send: Update channel ack_tick group_id=ReplicationGroupId(4294967316) bevy_tick=Tick { tick: 3442603 } tick=Tick(295)
2024-10-02T16:01:12.137028Z DEBUG lightyear::server::connection: Received server packet with tick: Tick(322)
2024-10-02T16:01:12.137075Z DEBUG lightyear::server::input::leafwing: received input message client_id=Netcode(3316667147651033357) action="PlayerInput" message.end_tick=Tick(322) message.diffs=[(Entity(Entity { index: 20, generation: 1 }), ActionState { disabled: false, action_data: {Run: ActionData { disabled: false, kind_data: DualAxis(DualAxisData { pair: Vec2(0.0, 0.0), update_pair: Vec2(0.0, 0.0), fixed_update_pair: Vec2(0.0, 0.0) }) }, CameraPan: ActionData { disabled: false, kind_data: DualAxis(DualAxisData { pair: Vec2(0.0, 0.0), update_pair: Vec2(0.0, 0.0), fixed_update_pair: Vec2(0.0, 0.0) }) }, Shoot: ActionData { disabled: false, kind_data: Button(ButtonData { state: Released, update_state: Released, fixed_update_state: Released }) }, Jump: ActionData { disabled: false, kind_data: Button(ButtonData { state: Released, update_state: Released, fixed_update_state: Released }) }} }, [[]])]
2024-10-02T16:01:12.137086Z DEBUG lightyear::server::input::leafwing: received input for entity: Entity { index: 20, generation: 1 }
thread 'Compute Task Pool (11)' panicked at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leafwing-input-manager-0.15.0/src/action_state/mod.rs:737:9:
assertion `left == right` failed
  left: DualAxis
 right: Button
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/panicking.rs:74:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/panicking.rs:367:5
   4: leafwing_input_manager::action_state::ActionState<A>::pressed
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leafwing-input-manager-0.15.0/src/action_state/mod.rs:737:9
   5: leafwing_input_manager::action_state::ActionState<A>::get_pressed::{{closure}}
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leafwing-input-manager-0.15.0/src/action_state/mod.rs:821:30
   6: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/ops/function.rs:294:13
   7: core::iter::traits::iterator::Iterator::find::check::{{closure}}
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/iter/traits/iterator.rs:2872:20
   8: core::iter::adapters::cloned::clone_try_fold::{{closure}}
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/iter/adapters/cloned.rs:29:21
   9: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/iter/traits/iterator.rs:2406:21
  10: <core::iter::adapters::cloned::Cloned<I> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/iter/adapters/cloned.rs:54:9
  11: core::iter::traits::iterator::Iterator::find
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/iter/traits/iterator.rs:2876:9
  12: <core::iter::adapters::filter::Filter<I,P> as core::iter::traits::iterator::Iterator>::next
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/iter/adapters/filter.rs:98:9
  13: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/alloc/src/vec/spec_from_iter_nested.rs:24:32
  14: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/alloc/src/vec/spec_from_iter.rs:33:9
  15: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/alloc/src/vec/mod.rs:3355:9
  16: core::iter::traits::iterator::Iterator::collect
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/iter/traits/iterator.rs:2001:9
  17: leafwing_input_manager::action_state::ActionState<A>::get_pressed
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leafwing-input-manager-0.15.0/src/action_state/mod.rs:822:14
  18: <lightyear::inputs::leafwing::input_message::InputMessage<A> as core::fmt::Display>::fmt::{{closure}}
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lightyear-0.17.1/src/inputs/leafwing/input_message.rs:39:21
  19: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/iter/adapters/map.rs:88:28
  20: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/slice/iter/macros.rs:232:27
  21: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/iter/adapters/map.rs:128:9
  22: core::iter::traits::iterator::Iterator::for_each
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/iter/traits/iterator.rs:813:9
  23: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/alloc/src/vec/mod.rs:3491:17
  24: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/alloc/src/vec/spec_extend.rs:26:9
  25: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/alloc/src/vec/spec_from_iter_nested.rs:60:9
  26: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/alloc/src/vec/spec_from_iter.rs:33:9
  27: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/alloc/src/vec/mod.rs:3355:9
  28: core::iter::traits::iterator::Iterator::collect
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/iter/traits/iterator.rs:2001:9
  29: <lightyear::inputs::leafwing::input_message::InputMessage<A> as core::fmt::Display>::fmt
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lightyear-0.17.1/src/inputs/leafwing/input_message.rs:47:14
  30: core::fmt::rt::Argument::fmt
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/fmt/rt.rs:177:76
  31: core::fmt::write
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/fmt/mod.rs:1186:21
  32: core::fmt::rt::Argument::fmt
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/fmt/rt.rs:177:76
  33: core::fmt::write
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/fmt/mod.rs:1186:21
  34: tracing_subscriber::fmt::format::Writer::write_fmt
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/fmt/format/mod.rs:514:9
  35: <tracing_subscriber::fmt::format::DefaultVisitor as tracing_core::field::Visit>::record_debug
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/fmt/format/mod.rs:1279:26
  36: <&T as tracing_core::field::Value>::record
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.32/src/field.rs:594:9
  37: tracing_core::field::ValueSet::record
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.32/src/field.rs:1006:23
  38: tracing_core::event::Event::record
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.32/src/event.rs:87:9
  39: <tracing_core::event::Event as tracing_subscriber::field::RecordFields>::record
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/field/mod.rs:163:9
  40: <&F as tracing_subscriber::field::RecordFields>::record
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/field/mod.rs:187:9
  41: <M as tracing_subscriber::fmt::format::FormatFields>::format_fields
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/fmt/format/mod.rs:1166:9
  42: <tracing_subscriber::fmt::fmt_layer::FmtContext<S,N> as tracing_subscriber::fmt::format::FormatFields>::format_fields
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/fmt/fmt_layer.rs:1033:9
  43: <tracing_subscriber::fmt::format::Format<tracing_subscriber::fmt::format::Full,T> as tracing_subscriber::fmt::format::FormatEvent<S,N>>::format_event
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/fmt/format/mod.rs:1021:13
  44: <tracing_subscriber::fmt::fmt_layer::Layer<S,N,E,W> as tracing_subscriber::layer::Layer<S>>::on_event::{{closure}}
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/fmt/fmt_layer.rs:965:16
  45: std::thread::local::LocalKey<T>::try_with
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/thread/local.rs:283:12
  46: std::thread::local::LocalKey<T>::with
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/thread/local.rs:260:9
  47: <tracing_subscriber::fmt::fmt_layer::Layer<S,N,E,W> as tracing_subscriber::layer::Layer<S>>::on_event
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/fmt/fmt_layer.rs:949:13
  48: tracing_core::event::Event::dispatch
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.32/src/event.rs:34:9
  49: lightyear::server::input::leafwing::receive_input_message::{{closure}}
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lightyear-0.17.1/src/server/input/leafwing.rs:139:45
  50: lightyear::server::input::leafwing::receive_input_message
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/macros.rs:872:13
  51: core::ops::function::FnMut::call_mut
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/ops/function.rs:166:5
  52: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/ops/function.rs:294:13
  53: <Func as bevy_ecs::system::function_system::SystemParamFunction<fn(F0,F1,F2,F3,F4) .> Out>>::run::call_inner
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.14.2/src/system/function_system.rs:710:21
  54: <Func as bevy_ecs::system::function_system::SystemParamFunction<fn(F0,F1,F2,F3,F4) .> Out>>::run
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.14.2/src/system/function_system.rs:713:17
  55: <bevy_ecs::system::function_system::FunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run_unsafe
             at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.14.2/src/system/function_system.rs:534:19
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Encountered a panic in system `lightyear::server::input::leafwing::receive_input_message<shared::input::PlayerInput>`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```
Currently I do not yet know the exact circumstances to replicate this.

**Comment by AndreasHGK** [comment]
Weirdly enough, I can quite reliably reproduce this bug in my codebase by adding `RUST_BACKTRACE=1 RUST_LOG="info,lightyear=debug"` before my cargo run command. Removing those env vars makes it so it no longer happens.

**Comment by AndreasHGK** [comment]
This error also shows up in the `avian_3d_character` example, only with the `RUST_LOG="info,lightyear=debug"` environment variable is set.

**Comment by cBournhonesque** [comment]
There's a problem in how you're setting up your leafwing inputs: 
```
assertion `left == right` failed
  left: DualAxis
 right: Button
 ```
 
Did you set the input_control_kind correctly? https://github.com/cBournhonesque/lightyear/blob/main/examples/bullet_prespawn/src/protocol.rs#L116

**Comment by AndreasHGK** [comment]
I believe it should be correct, I have used the same input struct in the offline version of my game prototype. The panic being present in one of the examples furthermore makes me think it may be a bug in either library.
Running the following command in the `examples/avian_3d_character` folder in this repository (latest commit) reproduces the panic every time for me:
```bash
RUST_LOG="info,lightyear=debug" cargo run -- server & cargo run -- client
```

**Comment by AndreasHGK** [comment]
This seems to be a bug in leafwing, my bad! For reference, the following test fails:
```rs
#[test]
fn test() {
    use bevy::reflect::Reflect;
    use leafwing_input_manager::{Actionlike, InputControlKind};

    #[derive(Reflect, Clone, PartialEq, Eq, Hash, Debug)]
    enum PlayerInput {
        Run,
        Jump,
        Shoot,
        CameraPan,
    }

    impl Actionlike for PlayerInput {
        fn input_control_kind(&self) -> InputControlKind {
            match self {
                Self::Run => InputControlKind::DualAxis,
                Self::Jump => InputControlKind::Button,
                Self::Shoot => InputControlKind::Button,
                Self::CameraPan => InputControlKind::DualAxis,
            }
        }
    }

    let mut state = ActionState::<PlayerInput>::default();
    state.set_axis_pair(&PlayerInput::Run, Vec2::ZERO);
    assert_eq!(state.get_pressed().len(), 0);
}
```

**Comment by AndreasHGK** [comment]
> thread 'Compute Task Pool (11)' panicked at /home/andreas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leafwing-input-manager-0.15.0/src/action_state/mod.rs:737:9:
> assertion `left == right` failed
>   left: DualAxis
>  right: Button
